-- Tech Priests 0.1.674-dev canonical standard-fluid doctrine.
-- Read-only machine context, fluidbox identity, shared-port collision safety,
-- source/sink discovery, and exact input/output proposals. It never changes a
-- recipe, fluid, inventory, construction task, movement request, or machine task.

local M={version="0.1.674-dev",storage_key="fluid_network_doctrine_0689",scan_interval=211,entity_cache_ticks=180,max_pairs_per_scan=6,max_machines=96,max_sources=192,service_radius_floor=28,service_radius_cap=96,proposal_ttl=60*20,read_only=true,input_output_proposals_integrated=true,port_collision_integrated=true,context_guard_integrated=true,fluid_item_policy_integrated=true,structured_scan_truth=true}
local MACHINE_TYPES={"assembling-machine","furnace","mining-drill","boiler","generator","reactor","rocket-silo"}
local FLUID_TYPES={"pipe","pipe-to-ground","pump","storage-tank","offshore-pump","assembling-machine","furnace","mining-drill","boiler","generator","reactor","rocket-silo"}
local function now()return game and game.tick or 0 end
local function valid(e)return e and e.valid end
local function safe(v)if v==nil then return"nil"end;local ok,s=pcall(tostring,v);return ok and s or"?"end
local function valid_pair(p)return type(p)=="table"and valid(p.station)and valid(p.priest)end
local function station_unit(p)return p and(p.station_unit or(valid(p.station)and p.station.unit_number))or nil end
local function pair_map()return storage and storage.tech_priests and storage.tech_priests.pairs_by_station or{}end
local function dist_sq(a,b)if not(a and b)then return math.huge end;local x=(a.x or 0)-(b.x or 0);local y=(a.y or 0)-(b.y or 0);return x*x+y*y end
local function same_pos(a,b)return a and b and math.abs((a.x or 0)-(b.x or 0))<=.15 and math.abs((a.y or 0)-(b.y or 0))<=.15 end
local function entity_key(e)return valid(e)and(e.unit_number and("unit:"..e.unit_number)or safe(e.surface and e.surface.index)..":"..safe(e.name)..":"..math.floor(e.position.x*10)..":"..math.floor(e.position.y*10))or nil end
function M.root()
 storage.tech_priests=storage.tech_priests or{};local r=storage.tech_priests[M.storage_key]or{version=M.version,enabled=true,read_only=true,input_output_proposals_integrated=true,port_collision_integrated=true,context_guard_integrated=true,fluid_item_policy_integrated=true,structured_scan_truth=true,stats={},recent={},entity_due={},reports={},cursor=0};storage.tech_priests[M.storage_key]=r;r.version=M.version
 if r.enabled==nil then r.enabled=true end;r.read_only=true;r.input_output_proposals_integrated=true;r.port_collision_integrated=true;r.context_guard_integrated=true;r.fluid_item_policy_integrated=true;r.structured_scan_truth=true;r.stats=r.stats or{};r.recent=r.recent or{};r.entity_due=r.entity_due or{};r.reports=r.reports or{};r.cursor=tonumber(r.cursor)or 0;return r
end
local function stat(k,n)local r=M.root();r.stats[k]=(tonumber(r.stats[k])or 0)+(tonumber(n)or 1)end
local function record(pair,action,detail)local r=M.root();r.recent[#r.recent+1]={tick=now(),station=safe(station_unit(pair)),action=tostring(action),detail=tostring(detail or"")};while#r.recent>160 do table.remove(r.recent,1)end;stat(action)end
local function fluidbox(e)local ok,b=pcall(function()return e.fluidbox end);return ok and b and b.valid and b or nil end
local function get_recipe(e)local ok,r=pcall(function()return e.get_recipe and e.get_recipe()end);return ok and r or nil end
local function recipe_fluids(recipe,field)
 local out={};local records;pcall(function()records=recipe and recipe[field]end);for _,rec in pairs(records or{})do local name=rec.name or rec[1];local kind=rec.type or(rec.name and"item");if kind=="fluid"and type(name)=="string"then out[#out+1]={name=name,amount=tonumber(rec.amount or rec.amount_min or rec[2])or 1,temperature=tonumber(rec.temperature)}end end;return out
end
local function segment_contents(box,index)local out={};if box and box.valid then pcall(function()out=box.get_fluid_segment_contents(index)or{}end)end;return type(out)=="table"and out or{}end
local function segment_id(box,index)local v;if box and box.valid then pcall(function()v=box.get_fluid_segment_id(index)end)end;return v end
local function capacity(box,index)local v=0;if box and box.valid then pcall(function()v=tonumber(box.get_capacity(index))or 0 end)end;return v end
local function prototype_record(box,index)local v;if box and box.valid then pcall(function()v=box.get_prototype(index)end)end;if type(v)=="table"and v.object_name==nil then for _,p in pairs(v)do if p then return p end end end;return v end
local function production_type(box,index)local p=prototype_record(box,index);local v;if p then pcall(function()v=p.production_type end)end;return v end
local function filter_name(box,index)
 local f;if box and box.valid then pcall(function()f=box.get_filter(index)end);if type(f)=="table"then f=f.name end;if not f then pcall(function()f=box.get_locked_fluid(index)end)end;if not f then local p=prototype_record(box,index);pcall(function()f=p and p.filter and p.filter.name end)end end;return type(f)=="string"and f~=""and f or nil
end
local function connection_records(box,index)
 local out={};local connections={};if box and box.valid then pcall(function()connections=box.get_pipe_connections(index)or{}end)end;for _,c in pairs(connections)do if type(c)=="table"then local owner;if c.target then pcall(function()owner=c.target.owner end)end;local p=c.target_position or c.position;out[#out+1]={position=p and{x=p.x,y=p.y}or nil,connected=c.target~=nil or valid(owner),target_owner=owner}end end;return out
end
local function free_targets(box,index)local out={};for _,c in ipairs(connection_records(box,index))do if c.position and not c.connected then out[#out+1]=c.position end end;return out end
local function requirement_for(index,box,inputs,outputs)
 local direction=production_type(box,index);local filter=filter_name(box,index);local contents=segment_contents(box,index);local function choose(list)
  if filter then for _,r in ipairs(list)do if r.name==filter then return r end end end
  for name,amount in pairs(contents)do if(tonumber(amount)or 0)>.001 then for _,r in ipairs(list)do if r.name==name then return r end end end end
  return#list==1 and list[1]or nil
 end
 if direction=="input"then return choose(inputs),"input"end;if direction=="output"then return choose(outputs),"output"end;if direction=="input-output"then local input=choose(inputs);return input or choose(outputs),input and"input"or"output"end
 local input=choose(inputs);if input then return input,"input"end;local output=choose(outputs);if output then return output,"output"end;return nil,direction or"unknown"
end
local function known_identity(record)local names={};if record.requirement and record.requirement.name then names[record.requirement.name]=true end;if record.filter then names[record.filter]=true end;for name,amount in pairs(record.contents or{})do if(tonumber(amount)or 0)>.001 then names[name]=true end end;return names end
local function port_records(e,inputs,outputs)
 local out={};local box=fluidbox(e);if not box then return out end;for index=1,#box do local req,direction=requirement_for(index,box,inputs or{},outputs or{});local connections=connection_records(box,index);local connected=false;for _,c in ipairs(connections)do if c.connected then connected=true break end end;out[#out+1]={index=index,direction=direction,requirement=req,filter=filter_name(box,index),contents=segment_contents(box,index),segment_id=segment_id(box,index),capacity=capacity(box,index),connections=connections,free_targets=free_targets(box,index),connected=connected}end;return out
end
local function touching_records(e,target,records)local out={};for _,rec in ipairs(records or{})do for _,c in ipairs(rec.connections or{})do if c.position and same_pos(c.position,target)then out[#out+1]=rec;break end end end;return out end
function M.validate_endpoint(e,index,target,fluid,records,allow_empty)
 if not(valid(e)and index and target and fluid)then return false,"invalid-endpoint"end;records=records or port_records(e,{},{});local touching=touching_records(e,target,records);if#touching==0 then return false,"target-not-on-fluidbox"end
 for _,rec in ipairs(touching)do local identities=known_identity(rec);local count=0;for name in pairs(identities)do count=count+1;if name~=fluid then return false,"fluidbox-"..rec.index..":different-fluid:"..name end end;if count==0 and not(allow_empty and(e.type=="pipe"or e.type=="pipe-to-ground"or e.type=="storage-tank"))then return false,"fluidbox-"..rec.index..":ambiguous-empty-unfiltered"end end
 stat(#touching>1 and"compatible_shared_ports"or"validated_endpoints");return true,#touching>1 and"compatible-shared-port"or"single-port"
end
local function service_radius(pair)local radius=tonumber(pair and pair.radius)or M.service_radius_floor;if valid_pair(pair)and type(_G.get_station_operating_radius)=="function"then local ok,v=pcall(_G.get_station_operating_radius,pair.station);if ok and tonumber(v)then radius=tonumber(v)end end;return math.max(8,math.min(math.max(radius,M.service_radius_floor),M.service_radius_cap))end
local function routed_find(surface,filters,category,key,ttl)local scanner=rawget(_G,"TechPriestsScanRouting0610")or package.loaded["scripts.core.scan_routing_0610"];if scanner and type(scanner.find_entities)=="function"then local entities=select(1,scanner.find_entities(surface,filters,{category=category,negative_key=key,negative_ttl=ttl or 300}));return entities or{}end;local ok,entities=pcall(function()return surface.find_entities_filtered(filters)end);return ok and entities or{}end
local function source_or_sink(pair,machine,fluid,direction)
 local radius=service_radius(pair);local p=pair.station.position;local entities=routed_find(machine.surface,{area={{p.x-radius,p.y-radius},{p.x+radius,p.y+radius}},force=machine.force,type=FLUID_TYPES,limit=M.max_sources},"standard-fluid-"..direction,"standard-fluid:"..direction..":"..safe(machine.surface.index)..":"..safe(machine.force.index)..":"..fluid,300);local best
 for _,e in pairs(entities)do if valid(e)and e~=machine then local records=port_records(e,{},{});for _,candidate in ipairs(records)do local identities=known_identity(candidate);local wrong=false;for name in pairs(identities)do if name~=fluid then wrong=true break end end;local amount=tonumber(candidate.contents and candidate.contents[fluid])or 0;local total=0;for _,n in pairs(candidate.contents or{})do total=total+(tonumber(n)or 0)end;local free=math.max(0,(tonumber(candidate.capacity)or 0)-total);local eligible=direction=="input"and amount>.001 or direction=="output"and not wrong and(free>.001 or next(identities)==nil)
   if eligible and not wrong then for _,target in ipairs(candidate.free_targets or{})do local ok=M.validate_endpoint(e,candidate.index,target,fluid,records,direction=="output");if ok then local score=dist_sq(e.position,machine.position)-(direction=="input"and math.min(amount,100000)*.001 or math.min(free,100000)*.001);if not best or score<best.score then best={entity=e,entity_name=e.name,entity_unit=e.unit_number,fluidbox_index=candidate.index,segment_id=candidate.segment_id,interfaces={target},amount=amount,free_capacity=free,score=score}end end end end
  end end end;return best
end
local function report_state(records)local missing,blocked={},{};for _,rec in ipairs(records)do if rec.requirement and rec.requirement.name then local amount=tonumber(rec.contents and rec.contents[rec.requirement.name])or 0;if rec.direction=="input"and not rec.connected and amount<=.001 then missing[#missing+1]=rec elseif rec.direction=="output"and not rec.connected and amount>.001 then blocked[#blocked+1]=rec end end end;return missing,blocked end
function M.inspect_machine(pair,machine,force)
 if not(valid_pair(pair)and valid(machine))then return nil,"invalid"end;local key=entity_key(machine);local r=M.root();if not force and key and(tonumber(r.entity_due[key])or 0)>now()then return r.reports[key],"cached"end;if key then r.entity_due[key]=now()+M.entity_cache_ticks end
 local recipe=get_recipe(machine);if not recipe then return nil,"no-recipe"end;local inputs=recipe_fluids(recipe,"ingredients");local outputs=recipe_fluids(recipe,"products");if#inputs==0 and#outputs==0 then return nil,"no-fluid-requirements"end;local records=port_records(machine,inputs,outputs);local missing,blocked=report_state(records);local report={version=M.version,tick=now(),read_only=true,machine=machine,machine_name=machine.name,machine_unit=machine.unit_number,station_unit=station_unit(pair),recipe_name=recipe.name,fluid_inputs=inputs,fluid_outputs=outputs,records=records,missing_inputs=missing,blocked_outputs=blocked,context_identity={surface_index=machine.surface.index,force_index=machine.force.index,machine_unit=machine.unit_number}};if key then r.reports[key]=report end;stat("machines-inspected");return report,"inspected"
end
local function proposals_for_report(pair,report)
 local inputs,outputs={},{};for _,rec in ipairs(report.missing_inputs or{})do local fluid=rec.requirement.name;local source=source_or_sink(pair,report.machine,fluid,"input");if source then local targets={};for _,target in ipairs(rec.free_targets or{})do local ok=M.validate_endpoint(report.machine,rec.index,target,fluid,report.records,false);if ok then targets[#targets+1]=target end end;if#targets>0 then inputs[#inputs+1]={version=M.version,tick=now(),expires_tick=now()+M.proposal_ttl,read_only=true,action="connect-fluid-input",direction="input",machine=report.machine,machine_name=report.machine_name,machine_unit=report.machine_unit,report_tick=report.tick,context_identity=report.context_identity,fluid=fluid,fluidbox_index=rec.index,connection_targets=targets,source=source,state="safe-source-found",port_collision_safe=true}end end end
 for _,rec in ipairs(report.blocked_outputs or{})do local fluid=rec.requirement.name;local sink=source_or_sink(pair,report.machine,fluid,"output");if sink then local targets={};for _,target in ipairs(rec.free_targets or{})do local ok=M.validate_endpoint(report.machine,rec.index,target,fluid,report.records,false);if ok then targets[#targets+1]=target end end;if#targets>0 then outputs[#outputs+1]={version=M.version,tick=now(),expires_tick=now()+M.proposal_ttl,read_only=true,action="connect-fluid-output",direction="output",machine=report.machine,machine_name=report.machine_name,machine_unit=report.machine_unit,report_tick=report.tick,context_identity=report.context_identity,fluid=fluid,fluidbox_index=rec.index,connection_targets=targets,sink=sink,state="safe-sink-found",port_collision_safe=true}end end end
 return inputs,outputs
end
function M.validate_proposal(pair,p)
 if not(valid_pair(pair)and type(p)=="table"and valid(p.machine)and p.context_identity and p.fluid and p.fluidbox_index)then return false,"invalid-proposal"end;if(tonumber(p.expires_tick)or 0)<now()then return false,"proposal-expired"end;if p.machine.surface~=pair.station.surface or p.machine.force~=pair.station.force then return false,"machine-context-mismatch"end;if p.context_identity.machine_unit and p.machine.unit_number~=p.context_identity.machine_unit then return false,"machine-unit-mismatch"end
 local report=M.inspect_machine(pair,p.machine,true);if not(report and report.context_identity.machine_unit==p.context_identity.machine_unit)then return false,"report-context-mismatch"end;local record;for _,rec in ipairs(report.records or{})do if rec.index==p.fluidbox_index and rec.requirement and rec.requirement.name==p.fluid then record=rec break end end;if not record then return false,"machine-port-no-longer-required"end
 local endpoint=p.direction=="input"and p.source or p.sink;if not(endpoint and valid(endpoint.entity)and endpoint.entity.surface==pair.station.surface and endpoint.entity.force==pair.station.force)then return false,"remote-endpoint-invalid"end;local machine_safe=false;for _,target in ipairs(p.connection_targets or{})do local ok=M.validate_endpoint(p.machine,p.fluidbox_index,target,p.fluid,report.records,false);if ok then machine_safe=true break end end;if not machine_safe then return false,"machine-port-unsafe"end
 local endpoint_records=port_records(endpoint.entity,{},{});local remote_safe=false;for _,target in ipairs(endpoint.interfaces or{})do local ok=M.validate_endpoint(endpoint.entity,endpoint.fluidbox_index,target,p.fluid,endpoint_records,p.direction=="output");if ok then remote_safe=true break end end;if not remote_safe then return false,"remote-port-unsafe"end;if p.direction=="input"then local amount=tonumber(segment_contents(fluidbox(endpoint.entity),endpoint.fluidbox_index)[p.fluid])or 0;if amount<=.001 then return false,"source-fluid-empty"end end;return true,"safe",report
end
function M.scan_pair(pair,force)
 if M.root().enabled==false or not valid_pair(pair)then return{processed=0,failed=not valid_pair(pair)and 1 or 0,detail="disabled-or-invalid"}end;if not force and now()<(tonumber(pair.fluid_network_scan_due_0689)or 0)then return{processed=0,acted=0,detail="cached"}end;pair.fluid_network_scan_due_0689=now()+M.scan_interval
 local radius=service_radius(pair);local p=pair.station.position;local machines=routed_find(pair.station.surface,{area={{p.x-radius,p.y-radius},{p.x+radius,p.y+radius}},force=pair.station.force,type=MACHINE_TYPES,limit=M.max_machines},"standard-fluid-machines","standard-fluid-machines:"..safe(pair.station.surface.index)..":"..safe(pair.station.force.index)..":"..safe(station_unit(pair)),180)
 local reports,inputs,outputs={},{},{};for _,machine in pairs(machines)do local report=M.inspect_machine(pair,machine,false);if report then reports[#reports+1]=report;local a,b=proposals_for_report(pair,report);for _,v in ipairs(a)do inputs[#inputs+1]=v end;for _,v in ipairs(b)do outputs[#outputs+1]=v end end end
 pair.machine_fluid_reports_0689=reports;pair.machine_fluid_network_0689=reports[1];pair.fluid_connection_proposals_0689=inputs;pair.fluid_output_sink_proposals_0694=outputs;record(pair,"pair-scan","machines="..#reports.." inputs="..#inputs.." outputs="..#outputs);return{processed=1,acted=0,waiting=#inputs+#outputs,detail="machines="..#reports}
end
local function patch_diagnostics()
 local d=rawget(_G,"TECH_PRIESTS_DIAGNOSTICS_BEHAVIOR_AUTHORITY_0468")or rawget(_G,"TechPriestsEmergencyDiagnostics0468");if not(d and type(d.pair_dump_lines)=="function")or d.fluid_network_doctrine_0689_wrapped then return false end;d.fluid_network_doctrine_0689_wrapped=true;local previous=d.pair_dump_lines;d.pair_dump_lines=function(...)local lines=previous(...);lines=type(lines)=="table"and lines or{};local r=M.root();lines[#lines+1]="PAIR-DUMP-0468 FLUID-NETWORK-0689 enabled="..safe(r.enabled).." read_only=true context_integrated=true collision_integrated=true inspected="..safe(r.stats["machines-inspected"]or 0);return lines end;return true
end
local function canonical_broker()
 local broker=rawget(_G,"TechPriestsRuntimeTickBroker0600")or package.loaded["scripts.core.runtime_tick_broker"];if not broker then local ok,m=pcall(require,"scripts.core.runtime_tick_broker");if not ok then return nil end;broker=m end;if not(broker and type(broker.install)=="function")then return nil end;local ok,installed=pcall(broker.install);if not(ok and installed==true)then return nil end;return broker
end
local function register_service()
 local broker=canonical_broker();if not(broker and type(broker.register_service)=="function")then return false end;local service=broker.register_service({name="fluid_network_doctrine_0689",category="readiness",interval=M.scan_interval,priority=72,budget=M.max_pairs_per_scan,note="read-only standard fluid machine context and exact input/output proposals",fn=function(_,budget)local processed,waiting,failed=0,0,0;for _,pair in pairs(pair_map())do if processed>=math.max(1,tonumber(budget)or M.max_pairs_per_scan)then break end;local ok,out=pcall(M.scan_pair,pair,false);processed=processed+1;if ok and type(out)=="table"then waiting=waiting+(tonumber(out.waiting)or 0)else failed=failed+1 end end;return{processed=processed,acted=0,waiting=waiting,failed=failed,detail="pairs="..processed}end});return service~=nil
end
function M.install()M.root();_G.TechPriestsFluidNetworkDoctrine0689=M;if not register_service()then return false end;patch_diagnostics();if log then log("[Tech-Priests recovery] read-only standard fluid doctrine armed; item logistics remain separate")end;return true end
return M
