-- scripts/core/roboport_readiness_0714.lua
-- Tech Priests 0.1.674-dev recovery.
-- Read-only doctrine for existing roboports. Placement effectiveness is observed
-- for diagnostics; construction and defense planners remain the placement authority.

local M={
 version="0.1.674-dev",storage_key="roboport_readiness_0714",
 scan_interval=60*5,cache_ticks=60*3,max_entities=96,target_repair_packs=10,
 read_only=true,structured_scan_truth=true,placement_authority=false,
 placement_effectiveness_observed=true,robot_population_monitor_only=true,
}
local function now()return game and game.tick or 0 end
local function valid(e)return e and e.valid end
local function safe(v)local ok,s=pcall(tostring,v);return ok and s or"?"end
local function valid_pair(p)return type(p)=="table"and valid(p.station)and valid(p.priest)end
local function station_unit(p)return p and(p.station_unit or(valid(p.station)and p.station.unit_number))or nil end
local function pair_map()return storage and storage.tech_priests and storage.tech_priests.pairs_by_station or{}end
local function key(e)return valid(e)and(e.unit_number and"unit:"..e.unit_number or e.surface.index..":"..e.name..":"..math.floor(e.position.x*10)..":"..math.floor(e.position.y*10))or nil end
function M.root()
 storage.tech_priests=storage.tech_priests or{}
 local r=storage.tech_priests[M.storage_key]or{version=M.version,enabled=true,stats={},reports={},scan_due={},entity_due={},cursor=0}
 storage.tech_priests[M.storage_key]=r;r.version=M.version;if r.enabled==nil then r.enabled=true end
 r.read_only=true;r.placement_authority=false;r.stats=r.stats or{};r.reports=r.reports or{};r.scan_due=r.scan_due or{};r.entity_due=r.entity_due or{};r.cursor=tonumber(r.cursor)or 0;return r
end
local function stat(k,n)local r=M.root();r.stats[k]=(tonumber(r.stats[k])or 0)+(tonumber(n)or 1)end
local function inv(e,id)if not(valid(e)and id and e.get_inventory)then return nil end;local ok,v=pcall(e.get_inventory,e,id);return ok and v and v.valid and v or nil end
local function contents(i)local out={};if not(i and i.valid)then return out end;local ok,t=pcall(i.get_contents,i);if not(ok and type(t)=="table")then return out end;for k,v in pairs(t)do local n,c;if type(k)=="string"then n=k;c=type(v)=="table"and tonumber(v.count or v.amount or v[2])or tonumber(v)elseif type(v)=="table"then n=v.name or v.item or v[1];c=tonumber(v.count or v.amount or v[2])end;if type(n)=="string"and(c or 0)>0 then out[#out+1]={name=n,count=c}end end;table.sort(out,function(a,b)return a.name<b.name end);return out end
local function item_type(n)local p=prototypes and prototypes.item and prototypes.item[n];local t;if p then pcall(function()t=p.type end)end;return t end
local function place_type(n)local p=prototypes and prototypes.item and prototypes.item[n];local e,t;if p then pcall(function()e=p.place_result end);if e then pcall(function()t=e.type end)end end;return t end
local function breakdown(i,robot)local r=robot and{logistic=0,construction=0,other=0,entries=contents(i)}or{repair_packs=0,other=0,entries=contents(i)};for _,x in ipairs(r.entries)do if robot then local t=place_type(x.name);if t=="logistic-robot"then r.logistic=r.logistic+x.count elseif t=="construction-robot"then r.construction=r.construction+x.count else r.other=r.other+x.count end elseif item_type(x.name)=="repair-tool"then r.repair_packs=r.repair_packs+x.count else r.other=r.other+x.count end end;return r end
local function compatible_tools(i)local out={};if not(i and i.valid)then return out end;for n in pairs(prototypes and prototypes.item or{})do if item_type(n)=="repair-tool"then local ok,v=pcall(i.can_insert,i,{name=n,count=1});if ok and v==true then out[#out+1]=n end end end;table.sort(out);return out end
function M.connected_item_automation(e)
 if not valid(e)then return false,{}end;local b;pcall(function()b=e.bounding_box end);local p=e.position;local area=b and{{b.left_top.x-3,b.left_top.y-3},{b.right_bottom.x+3,b.right_bottom.y+3}}or{{p.x-3,p.y-3},{p.x+3,p.y+3}};local found={};local nearby={};pcall(function()nearby=e.surface.find_entities_filtered{area=area,force=e.force,type={"inserter","loader","loader-1x1"},limit=64}or{}end);for _,x in pairs(nearby)do if x.type=="inserter"then local a,d;pcall(function()a=x.pickup_target end);pcall(function()d=x.drop_target end);if a==e or d==e then found[#found+1]="inserter:"..safe(x.unit_number)end else local c;pcall(function()c=x.loader_container end);if c==e then found[#found+1]="loader:"..safe(x.unit_number)end end end;return#found>0,found
end
local function cell(e)local c;pcall(function()c=e.logistic_cell end);if not c then return{present=false}end;local n,charging={};pcall(function()n=c.logistic_network end);pcall(function()charging=c.charging_robots or{}end);local cc=0;for _,r in pairs(type(charging)=="table"and charging or{})do if valid(r)then cc=cc+1 end end;local out={present=true,cell=c,network=n,network_present=n~=nil,charging_count=cc,logistic_radius=tonumber(c.logistic_radius)or 0,construction_radius=tonumber(c.construction_radius)or 0};pcall(function()out.stationed_logistic=tonumber(c.stationed_logistic_robot_count)or 0 end);pcall(function()out.stationed_construction=tonumber(c.stationed_construction_robot_count)or 0 end);return out end
local function network(c)local n=c and c.network;if not n then return{present=false,all_logistic=0,all_construction=0}end;local r={present=true,network=n};for field,source in pairs{available_logistic="available_logistic_robots",all_logistic="all_logistic_robots",available_construction="available_construction_robots",all_construction="all_construction_robots"}do pcall(function()r[field]=tonumber(n[source])or 0 end)end;local cells={};pcall(function()cells=n.cells or{}end);r.cell_count=0;for _,x in pairs(cells)do if x and x.valid then r.cell_count=r.cell_count+1 end end;return r end
local function energy(e)local r={connected=false,energy=0,buffer=0,recharge_minimum=0};if e.is_connected_to_electric_network then pcall(function()r.connected=e.is_connected_to_electric_network()end)end;pcall(function()r.energy=tonumber(e.energy)or 0 end);pcall(function()r.buffer=tonumber(e.electric_buffer_size)or 0 end);pcall(function()r.recharge_minimum=tonumber(e.prototype.recharge_minimum)or 0 end);return r end
function M.inspect_entity(pair,e,force)
 if not(valid_pair(pair)and valid(e)and e.type=="roboport")then return nil,"invalid"end;local r=M.root();local k=key(e);if not force and k and(r.entity_due[k]or 0)>now()then return r.reports[k],"cached"end;if k then r.entity_due[k]=now()+M.cache_ticks end
 local ids=defines and defines.inventory or{};local robot_inv=inv(e,ids.roboport_robot);local material_inv=inv(e,ids.roboport_material);local robots=breakdown(robot_inv,true);local materials=breakdown(material_inv,false);local tools=compatible_tools(material_inv);local automated,reasons=M.connected_item_automation(e);local c=cell(e);local n=network(c);local power=energy(e);local target=M.target_repair_packs;local state,severity
 if not(robot_inv and material_inv)then state,severity="inventory-unavailable","blocked"elseif not(c.present and n.present)then state,severity="logistic-network-missing","blocked"elseif not power.connected then state,severity="electric-network-missing","blocked"elseif power.energy<math.max(1,power.recharge_minimum*.25)then state,severity="energy-buffer-low","blocked"elseif automated then state,severity="external-item-automation-owned","monitor"elseif(n.all_construction or 0)<=0 then state,severity="no-construction-robots-monitor","monitor"elseif#tools==0 then state,severity="no-compatible-repair-pack","blocked"elseif materials.repair_packs>=target then state,severity="repair-packs-sufficient","ready"else state,severity="manual-repair-pack-service-eligible","eligible"end
 local report={version=M.version,tick=now(),read_only=true,placement_authority=false,placement_effectiveness_observed=true,entity=e,entity_name=e.name,entity_unit=e.unit_number,station_unit=station_unit(pair),state=state,severity=severity,robot_inventory=robot_inv,robots=robots,material_inventory=material_inv,materials=materials,compatible_repair_packs=tools,repair_pack_target=target,repair_pack_missing=math.max(0,target-materials.repair_packs),connected_item_automation=automated,automation_reasons=reasons,cell=c,network=n,energy=power,coverage={logistic_radius=c.logistic_radius or 0,construction_radius=c.construction_radius or 0,charging_count=c.charging_count or 0,network_cell_count=n.cell_count or 0},robot_population_monitor_only=true}
 if k then r.reports[k]=report end;stat("entities-inspected");stat("state-"..state);return report,"inspected"
end
local function radius(pair)local v=tonumber(pair.radius)or 28;if type(_G.get_station_operating_radius)=="function"then local ok,n=pcall(_G.get_station_operating_radius,pair.station);if ok and tonumber(n)then v=tonumber(n)end end;return math.max(28,math.min(v,96))end
function M.scan_pair(pair,force)
 if M.root().enabled==false or not valid_pair(pair)then return 0 end;local r=M.root();local k=tostring(station_unit(pair)or"?");if not force and(r.scan_due[k]or 0)>now()then return#(pair.roboport_reports_0714 or{})end;r.scan_due[k]=now()+M.scan_interval;local rad=radius(pair);local p=pair.station.position;local list={};pcall(function()list=pair.station.surface.find_entities_filtered{area={{p.x-rad,p.y-rad},{p.x+rad,p.y+rad}},force=pair.station.force,type="roboport",limit=M.max_entities}or{}end);local reports={};local eligible,blocked=0,0;for _,e in pairs(list)do local q=M.inspect_entity(pair,e,false);if q then reports[#reports+1]=q;if q.state=="manual-repair-pack-service-eligible"then eligible=eligible+1 end;if q.severity=="blocked"then blocked=blocked+1 end end end;pair.roboport_reports_0714=reports;pair.roboport_summary_0714={version=M.version,tick=now(),inspected=#reports,eligible=eligible,blocked=blocked,read_only=true,placement_authority=false};stat("pair-scans");return#reports
end
function M.service_pair(pair,force)if not valid_pair(pair)then return{processed=0,failed=1,detail="invalid-pair"}end;local n=M.scan_pair(pair,force==true);local s=pair.roboport_summary_0714 or{};return{processed=1,acted=0,failed=0,detail="inspected="..n.." eligible="..(s.eligible or 0).." blocked="..(s.blocked or 0)}end
local function register_service()local b=rawget(_G,"TechPriestsRuntimeTickBroker0600");if not(b and type(b.register_service)=="function")then return false end;local service=b.register_service{name="roboport_readiness_0714",category="machine-logistics",interval=223,priority=78,budget=6,note="read-only existing-roboport readiness and placement-effectiveness observation",fn=function(_,budget)local list={};for k,p in pairs(pair_map())do if valid_pair(p)then list[#list+1]={key=tostring(k),pair=p}end end;table.sort(list,function(a,c)return a.key<c.key end);local r=M.root();local limit=math.min(#list,math.max(0,math.floor(tonumber(budget)or 6)));if limit==0 then return{processed=0,acted=0,detail="no-pairs"}end;local start=r.cursor%#list+1;local failed=0;for i=0,limit-1 do if not pcall(M.scan_pair,list[((start+i-1)%#list)+1].pair,false)then failed=failed+1 end end;r.cursor=(start+limit-2)%#list+1;return{processed=limit,acted=0,failed=failed,exhausted=#list>limit,detail="pairs="..limit.." failed="..failed}end};return service~=nil end
function M.install()M.root();_G.TechPriestsRoboportReadiness0714=M;_G.tech_priests_roboport_inspect_0714=M.inspect_entity;if not register_service()then return false end;if log then log("[Tech-Priests recovery] read-only roboport readiness armed; placement and robot population remain external")end;return true end
return M
