-- prototypes/gui_sprites.lua
-- Tech Priests 0.1.536
-- Registers only retained GUI utility sprites and portrait sheets.
-- The rejected outer frame kit/ornate rails were removed in 0.1.487.

local sprites = {
  { type = "sprite", name = "tech-priests-gui-controls-normal-01-round-button-off", filename = "__tech-priests__/graphics/gui/controls/normal/01_round_button_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-02-round-button-on", filename = "__tech-priests__/graphics/gui/controls/normal/02_round_button_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-03-rect-button-off", filename = "__tech-priests__/graphics/gui/controls/normal/03_rect_button_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-04-rect-button-on", filename = "__tech-priests__/graphics/gui/controls/normal/04_rect_button_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-05-toggle-switch-off", filename = "__tech-priests__/graphics/gui/controls/normal/05_toggle_switch_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-06-toggle-switch-on", filename = "__tech-priests__/graphics/gui/controls/normal/06_toggle_switch_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-07-rotary-knob-off", filename = "__tech-priests__/graphics/gui/controls/normal/07_rotary_knob_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-08-rotary-knob-on", filename = "__tech-priests__/graphics/gui/controls/normal/08_rotary_knob_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-09-lever-switch-off", filename = "__tech-priests__/graphics/gui/controls/normal/09_lever_switch_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-10-lever-switch-on", filename = "__tech-priests__/graphics/gui/controls/normal/10_lever_switch_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-11-warning-lamp-off", filename = "__tech-priests__/graphics/gui/controls/normal/11_warning_lamp_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-12-warning-lamp-on", filename = "__tech-priests__/graphics/gui/controls/normal/12_warning_lamp_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-13-slider-off", filename = "__tech-priests__/graphics/gui/controls/normal/13_slider_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-14-slider-on", filename = "__tech-priests__/graphics/gui/controls/normal/14_slider_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-15-gauge-off", filename = "__tech-priests__/graphics/gui/controls/normal/15_gauge_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-normal-16-gauge-on", filename = "__tech-priests__/graphics/gui/controls/normal/16_gauge_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-01-round-button-off", filename = "__tech-priests__/graphics/gui/controls/disabled/01_round_button_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-02-round-button-on", filename = "__tech-priests__/graphics/gui/controls/disabled/02_round_button_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-03-rect-button-off", filename = "__tech-priests__/graphics/gui/controls/disabled/03_rect_button_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-04-rect-button-on", filename = "__tech-priests__/graphics/gui/controls/disabled/04_rect_button_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-05-toggle-switch-off", filename = "__tech-priests__/graphics/gui/controls/disabled/05_toggle_switch_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-06-toggle-switch-on", filename = "__tech-priests__/graphics/gui/controls/disabled/06_toggle_switch_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-07-rotary-knob-off", filename = "__tech-priests__/graphics/gui/controls/disabled/07_rotary_knob_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-08-rotary-knob-on", filename = "__tech-priests__/graphics/gui/controls/disabled/08_rotary_knob_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-09-lever-switch-off", filename = "__tech-priests__/graphics/gui/controls/disabled/09_lever_switch_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-10-lever-switch-on", filename = "__tech-priests__/graphics/gui/controls/disabled/10_lever_switch_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-11-warning-lamp-off", filename = "__tech-priests__/graphics/gui/controls/disabled/11_warning_lamp_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-12-warning-lamp-on", filename = "__tech-priests__/graphics/gui/controls/disabled/12_warning_lamp_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-13-slider-off", filename = "__tech-priests__/graphics/gui/controls/disabled/13_slider_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-14-slider-on", filename = "__tech-priests__/graphics/gui/controls/disabled/14_slider_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-15-gauge-off", filename = "__tech-priests__/graphics/gui/controls/disabled/15_gauge_off.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-controls-disabled-16-gauge-on", filename = "__tech-priests__/graphics/gui/controls/disabled/16_gauge_on.png", width = 336, height = 264, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-01", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_01.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-02", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_02.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-03", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_03.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-04", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_04.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-05", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_05.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-06", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_06.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-07", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_07.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-08", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_08.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-09", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_09.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-10", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_10.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-11", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_11.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-boot-spinner-0526-12", filename = "__tech-priests__/graphics/gui/icons/boot_spinner_0526/boot_spinner_12.png", width = 128, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-mechanical-skull-gear-emblem", filename = "__tech-priests__/graphics/gui/icons/mechanical_skull_gear_emblem.png", width = 1017, height = 1034, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-portrait-tech-priest-augmented-sheet-a", filename = "__tech-priests__/graphics/gui/portraits/tech_priest_augmented_portrait_sheet_a.png", width = 1235, height = 1233, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-portrait-baseline-human-sheet", filename = "__tech-priests__/graphics/gui/portraits/baseline_human_portrait_sheet.png", width = 1242, height = 1235, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-portraits-alternative-human-augmented-portrait-sheet-c", filename = "__tech-priests__/graphics/gui/portraits/alternative_human_augmented_portrait_sheet_c.png", width = 1249, height = 1230, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-portrait-alternative-human-augmented-sheet-c", filename = "__tech-priests__/graphics/gui/portraits/alternative_human_augmented_portrait_sheet_c.png", width = 1249, height = 1230, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-portraits-planetary-magos-portrait-sheet-a", filename = "__tech-priests__/graphics/gui/portraits/planetary_magos_portrait_sheet_a.png", width = 1312, height = 1001, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-portrait-planetary-magos-sheet-a", filename = "__tech-priests__/graphics/gui/portraits/planetary_magos_portrait_sheet_a.png", width = 1312, height = 1001, flags = { "icon" } },
  -- 0.1.536 Cogitator sliced GUI frame sprites BEGIN
  { type = "sprite", name = "tech-priests-gui-frame-0536-corner-top-left", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/corner_top_left.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-top-rail-left", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_left.png", width = 80, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-top-center-emblem", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_center_emblem.png", width = 96, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-top-rail-right", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_right.png", width = 80, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-corner-top-right", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/corner_top_right.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-left-column", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/left_column.png", width = 64, height = 256, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-right-column", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/right_column.png", width = 64, height = 256, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-corner-bottom-left", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/corner_bottom_left.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-bottom-rail-left", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_left.png", width = 80, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-bottom-center-emblem", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_center_emblem.png", width = 96, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-bottom-rail-right", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_right.png", width = 80, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-corner-bottom-right", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/corner_bottom_right.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-tl", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_tl.png", width = 20, height = 20, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-t", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_t.png", width = 216, height = 20, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-tr", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_tr.png", width = 20, height = 20, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-l", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_l.png", width = 20, height = 216, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-display-center", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_display_center.png", width = 216, height = 216, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-r", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_r.png", width = 20, height = 216, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-bl", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_bl.png", width = 20, height = 20, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-b", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_b.png", width = 216, height = 20, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-br", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_br.png", width = 20, height = 20, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0536-inner-bezel-full", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/inner_bezel_full.png", width = 256, height = 256, flags = { "icon" } },
  -- 0.1.540 segmented non-distorting Cogitator rail/column sprites BEGIN
  { type = "sprite", name = "tech-priests-gui-frame-0540-top-rail-left-cap-a", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_left_cap_a.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-top-rail-left-mid", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_left_mid.png", width = 32, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-top-rail-left-cap-b", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_left_cap_b.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-top-rail-right-cap-a", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_right_cap_a.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-top-rail-right-mid", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_right_mid.png", width = 32, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-top-rail-right-cap-b", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/top_rail_right_cap_b.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-bottom-rail-left-cap-a", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_left_cap_a.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-bottom-rail-left-mid", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_left_mid.png", width = 32, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-bottom-rail-left-cap-b", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_left_cap_b.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-bottom-rail-right-cap-a", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_right_cap_a.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-bottom-rail-right-mid", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_right_mid.png", width = 32, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-bottom-rail-right-cap-b", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/bottom_rail_right_cap_b.png", width = 24, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-left-column-cap-top", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/left_column_cap_top.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-left-column-mid", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/left_column_mid.png", width = 64, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-left-column-cap-bottom", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/left_column_cap_bottom.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-right-column-cap-top", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/right_column_cap_top.png", width = 64, height = 64, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-right-column-mid", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/right_column_mid.png", width = 64, height = 128, flags = { "icon" } },
  { type = "sprite", name = "tech-priests-gui-frame-0540-right-column-cap-bottom", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/slices_384/right_column_cap_bottom.png", width = 64, height = 64, flags = { "icon" } },
  -- 0.1.540 segmented non-distorting Cogitator rail/column sprites END
  { type = "sprite", name = "tech-priests-gui-frame-0536-source-384", filename = "__tech-priests__/graphics/gui/cogitator_frame_0536/source/gui_frame_clean_source_384.png", width = 384, height = 384, flags = { "icon" } },
  -- 0.1.536 Cogitator sliced GUI frame sprites END
}

data:extend(sprites)
