#!/usr/bin/env python3
"""
Stage 4 lifecycle/destruction scanner for Tech Priests.

This read-only scanner inventories paths that may destroy, create, replace,
teleport, recall, orphan, seal, or otherwise invalidate Tech-Priest pair state.

Run from repository root:

    python tools/audit_lifecycle_destruction.py

Outputs:

    tech-priests_src/docs/CODEBASE_AUDIT_STAGE4_LIFECYCLE_DESTRUCTION_REPORT.md
    tech-priests_src/docs/CODEBASE_AUDIT_STAGE4_LIFECYCLE_DESTRUCTION_REPORT.json
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

ROOT = Path("tech-priests_src")
MD = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE4_LIFECYCLE_DESTRUCTION_REPORT.md")
JSON_OUT = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE4_LIFECYCLE_DESTRUCTION_REPORT.json")

PATTERNS = [
    ("destroy_call", re.compile(r"\.\s*destroy\s*\(")),
    ("raise_destroy", re.compile(r"raise_destroy\b|script_raised_destroy")),
    ("create_entity", re.compile(r"\.\s*create_entity\s*\(")),
    ("teleport", re.compile(r"\.\s*teleport\s*\(")),
    ("respawn_pair_priest", re.compile(r"respawn_pair_priest")),
    ("remove_pair_for_entity", re.compile(r"remove_pair_for_entity")),
    ("create_pair", re.compile(r"create_pair")),
    ("stuck", re.compile(r"stuck", re.IGNORECASE)),
    ("recall", re.compile(r"recall", re.IGNORECASE)),
    ("orphan", re.compile(r"orphan", re.IGNORECASE)),
    ("missing_priest", re.compile(r"missing[_%-]?priest", re.IGNORECASE)),
    ("destructible_write", re.compile(r"\.\s*destructible\s*=")),
    ("active_false", re.compile(r"\.\s*active\s*=\s*false\b|\bactive\s*=\s*false\b")),
    ("proxy_lifecycle", re.compile(r"proxy", re.IGNORECASE)),
    ("lifecycle_seal", re.compile(r"lifecycle[_%-]?seal|priest_lifecycle_seal", re.IGNORECASE)),
]

@dataclass
class Hit:
    path: str
    line: int
    kind: str
    classification: str
    source: str
    context_before: List[str]
    context_after: List[str]


def iter_lua(root: Path) -> Iterable[Path]:
    for path in root.rglob("*.lua"):
        if ".git" in path.parts or "__pycache__" in path.parts:
            continue
        yield path


def classify(path: str, kind: str, blob: str) -> str:
    p = path.replace("\\", "/").lower()
    b = blob.lower()
    if "priest_lifecycle_seal" in p or "lifecycle_seal" in b:
        return "lifecycle-seal-authority"
    if "proxy" in b:
        return "proxy-lifecycle-review"
    if "gui" in p or "player.gui" in b:
        return "gui-element-lifecycle"
    if "render" in b or "rendering" in b or "beam" in b or "line" in b or "text" in b:
        return "rendering-lifecycle"
    if "station" in b and ("pickup" in b or "mined" in b or "died" in b or "destroy" in b):
        return "station-authorized-cleanup-review"
    if kind in {"respawn_pair_priest", "remove_pair_for_entity", "create_pair", "missing_priest", "orphan"}:
        return "pair-lifecycle-review"
    if kind in {"stuck", "recall", "teleport"}:
        return "movement-recovery-lifecycle-review"
    if kind == "destroy_call":
        return "destroy-call-review"
    if kind == "create_entity":
        return "entity-creation-review"
    if kind == "destructible_write" or kind == "active_false":
        return "entity-state-write-review"
    return "lifecycle-reference-review"


def scan_file(path: Path, root: Path, context_lines: int) -> List[Hit]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    rel = path.relative_to(root).as_posix()
    hits: List[Hit] = []
    for idx, line in enumerate(lines, start=1):
        for kind, pat in PATTERNS:
            if pat.search(line):
                before = lines[max(0, idx - 1 - context_lines):idx - 1]
                after = lines[idx:min(len(lines), idx + context_lines)]
                blob = "\n".join(before + [line] + after)
                hits.append(Hit(rel, idx, kind, classify(rel, kind, blob), line.strip(), before, after))
    return hits


def scan(root: Path, context_lines: int) -> List[Hit]:
    hits: List[Hit] = []
    for path in iter_lua(root):
        hits.extend(scan_file(path, root, context_lines))
    hits.sort(key=lambda h: (h.classification, h.path.lower(), h.line, h.kind))
    return hits


def counts_by(hits: Sequence[Hit], attr: str) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for h in hits:
        key = getattr(h, attr)
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def markdown(root: Path, hits: Sequence[Hit]) -> str:
    lines: List[str] = []
    lines.append("# Stage 4 Lifecycle and Destruction Scanner Report")
    lines.append("")
    lines.append("Generated by `tools/audit_lifecycle_destruction.py`.")
    lines.append("")
    lines.append(f"- Source root: `{root.as_posix()}`")
    lines.append(f"- Total lifecycle/destruction hits: `{len(hits)}`")
    lines.append("")
    lines.append("## Counts by classification")
    lines.append("")
    lines.append("| Classification | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(hits, "classification").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Counts by kind")
    lines.append("")
    lines.append("| Kind | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(hits, "kind").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Hits")
    lines.append("")
    lines.append("| File | Line | Kind | Classification | Source |")
    lines.append("|---|---:|---|---|---|")
    for h in hits:
        src = h.source.replace("|", "\\|")
        lines.append(f"| `{h.path}` | {h.line} | `{h.kind}` | `{h.classification}` | `{src}` |")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("This scanner is intentionally broad. GUI/rendering destroys are not the same as priest destroys. Proxy lifecycle is not the same as visible-priest lifecycle. The next Stage 4 pass should separate visible-priest destruction, station-authorized cleanup, proxy lifecycle, rendering cleanup, and GUI element destruction.")
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Audit lifecycle/destruction surfaces")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--markdown", default=str(MD))
    parser.add_argument("--json", default=str(JSON_OUT))
    parser.add_argument("--context", type=int, default=6)
    args = parser.parse_args(argv)
    root = Path(args.root)
    if not root.exists():
        raise SystemExit(f"missing source root: {root}")
    hits = scan(root, max(0, args.context))
    md = Path(args.markdown)
    js = Path(args.json)
    md.parent.mkdir(parents=True, exist_ok=True)
    js.parent.mkdir(parents=True, exist_ok=True)
    md.write_text(markdown(root, hits), encoding="utf-8")
    js.write_text(json.dumps({
        "source_root": root.as_posix(),
        "total_hits": len(hits),
        "counts_by_classification": counts_by(hits, "classification"),
        "counts_by_kind": counts_by(hits, "kind"),
        "hits": [asdict(h) for h in hits],
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {root}; lifecycle/destruction hits={len(hits)}")
    print(f"Wrote {md}")
    print(f"Wrote {js}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
