#!/usr/bin/env python3
"""
Audit work queue / reservation category usage.

This read-only scanner helps decide whether mismatches such as work queue having
`emergency` while work reservations omit it are actually reachable.

Run from repository root:

    python tools/audit_work_category_usage.py

Outputs:

    tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_WORK_CATEGORY_USAGE.md
    tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_WORK_CATEGORY_USAGE.json
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

ROOT = Path("tech-priests_src")
MD = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_WORK_CATEGORY_USAGE.md")
JSON_OUT = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_WORK_CATEGORY_USAGE.json")

CATEGORIES = ["repair", "sanctify", "resource", "construction", "pickup", "emergency", "combat", "logistics", "machine-logistics"]
PATTERNS = [
    ("work_queue_submit", re.compile(r"\.\s*submit\s*\(\s*['\"]([^'\"]+)['\"]")),
    ("work_queue_claim_nearest", re.compile(r"\.\s*claim_nearest\s*\([^\n]*['\"]([^'\"]+)['\"]")),
    ("reservation_claim", re.compile(r"\.\s*claim\s*\(\s*['\"]([^'\"]+)['\"]")),
    ("reservation_release", re.compile(r"\.\s*release\s*\(\s*['\"]([^'\"]+)['\"]")),
    ("literal_category", re.compile(r"['\"](" + "|".join(re.escape(c) for c in CATEGORIES) + r")['\"]")),
]

@dataclass
class Hit:
    path: str
    line: int
    kind: str
    category: str
    source: str


def iter_lua(root: Path) -> Iterable[Path]:
    for path in root.rglob("*.lua"):
        if ".git" in path.parts or "__pycache__" in path.parts:
            continue
        yield path


def scan(root: Path) -> List[Hit]:
    hits: List[Hit] = []
    for path in iter_lua(root):
        rel = path.relative_to(root).as_posix()
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        for idx, line in enumerate(lines, start=1):
            for kind, pat in PATTERNS:
                for m in pat.finditer(line):
                    category = m.group(1)
                    hits.append(Hit(rel, idx, kind, category, line.strip()))
    hits.sort(key=lambda h: (h.category, h.kind, h.path.lower(), h.line))
    return hits


def counts_by(hits: Sequence[Hit], attr: str) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for h in hits:
        key = getattr(h, attr)
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def md_report(root: Path, hits: Sequence[Hit]) -> str:
    emergency = [h for h in hits if h.category == "emergency"]
    lines: List[str] = []
    lines.append("# Stage 3 Work Category Usage Report")
    lines.append("")
    lines.append("Generated by `tools/audit_work_category_usage.py`.")
    lines.append("")
    lines.append(f"- Source root: `{root.as_posix()}`")
    lines.append(f"- Total category hits: `{len(hits)}`")
    lines.append(f"- Emergency category hits: `{len(emergency)}`")
    lines.append("")
    lines.append("## Counts by category")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(hits, "category").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Counts by kind")
    lines.append("")
    lines.append("| Kind | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(hits, "kind").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Emergency hits")
    lines.append("")
    if emergency:
        lines.append("| File | Line | Kind | Source |")
        lines.append("|---|---:|---|---|")
        for h in emergency:
            src = h.source.replace("|", "\\|")
            lines.append(f"| `{h.path}` | {h.line} | `{h.kind}` | `{src}` |")
    else:
        lines.append("No emergency category hits found.")
    lines.append("")
    lines.append("## All hits")
    lines.append("")
    lines.append("| Category | File | Line | Kind | Source |")
    lines.append("|---|---|---:|---|---|")
    for h in hits:
        src = h.source.replace("|", "\\|")
        lines.append(f"| `{h.category}` | `{h.path}` | {h.line} | `{h.kind}` | `{src}` |")
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Audit work category usage")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--markdown", default=str(MD))
    parser.add_argument("--json", default=str(JSON_OUT))
    args = parser.parse_args(argv)
    root = Path(args.root)
    if not root.exists():
        raise SystemExit(f"missing source root: {root}")
    hits = scan(root)
    md = Path(args.markdown)
    js = Path(args.json)
    md.parent.mkdir(parents=True, exist_ok=True)
    js.parent.mkdir(parents=True, exist_ok=True)
    md.write_text(md_report(root, hits), encoding="utf-8")
    js.write_text(json.dumps({
        "source_root": root.as_posix(),
        "total_hits": len(hits),
        "counts_by_category": counts_by(hits, "category"),
        "counts_by_kind": counts_by(hits, "kind"),
        "hits": [asdict(h) for h in hits],
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {root}; category hits={len(hits)}")
    print(f"Wrote {md}")
    print(f"Wrote {js}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
