#!/usr/bin/env python3
"""
Second-pass direct command site scanner for Tech Priests.

The first direct-command scanner counts every set_command / defines.command /
go_to_location reference. That is useful for recall, but too noisy for repair.
This scanner groups likely command-issuing call sites by nearby source block so
Stage 3 can focus on actual direct command owners.

Run from repository root:

    python tools/audit_direct_command_sites.py

Outputs:

    tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_SITES.md
    tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_SITES.json
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

ROOT = Path("tech-priests_src")
MD = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_SITES.md")
JSON_OUT = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_SITES.json")

ISSUE_PATTERNS = [
    ("commandable.set_command", re.compile(r"\bcommandable\s*\.\s*set_command\s*\(")),
    ("entity.commandable.set_command", re.compile(r"\.\s*commandable\s*\.\s*set_command\s*\(")),
    ("entity.set_command", re.compile(r"\.\s*set_command\s*\(")),
    ("global issue_priest_command assignment", re.compile(r"\bissue_priest_command\s*=\s*function\b|_G\.issue_priest_command\s*=\s*function\b")),
    ("global issue_priest_command call", re.compile(r"\bissue_priest_command\s*\(")),
]

@dataclass
class Site:
    path: str
    line: int
    kind: str
    classification: str
    source: str
    context: List[str]


def iter_lua(root: Path) -> Iterable[Path]:
    for path in root.rglob("*.lua"):
        if ".git" in path.parts or "__pycache__" in path.parts:
            continue
        yield path


def classify(path: str, context: str) -> str:
    p = path.replace("\\", "/").lower()
    c = context.lower()
    if p.endswith("scripts/core/movement_controller.lua"):
        return "canonical-movement-controller"
    if "tech_priests_request_movement_0418" in c or "tech_priests_route_ground_command_0429" in c:
        return "route-first-or-movement-request-fallback"
    if "defines.command.stop" in c:
        return "direct-stop-command"
    if "defines.command.attack" in c:
        return "combat-attack-command-wrapper"
    if "go_to_location" in c:
        return "direct-go-to-location-command"
    if "issue_priest_command" in c:
        return "issue-priest-command-wrapper-or-call"
    return "direct-command-review"


def scan_file(path: Path, root: Path, context_lines: int) -> List[Site]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    rel = path.relative_to(root).as_posix()
    sites: List[Site] = []
    seen: set[Tuple[str, int, str]] = set()
    for idx, line in enumerate(lines, start=1):
        for kind, pat in ISSUE_PATTERNS:
            if not pat.search(line):
                continue
            before_i = max(0, idx - 1 - context_lines)
            after_i = min(len(lines), idx + context_lines)
            context = lines[before_i:after_i]
            cls = classify(rel, "\n".join(context))
            key = (rel, idx, kind)
            if key in seen:
                continue
            seen.add(key)
            sites.append(Site(rel, idx, kind, cls, line.strip(), context))
    return sites


def scan(root: Path, context_lines: int) -> List[Site]:
    sites: List[Site] = []
    for path in iter_lua(root):
        sites.extend(scan_file(path, root, context_lines))
    sites.sort(key=lambda s: (s.path.lower(), s.line, s.kind))
    return sites


def counts_by(sites: Sequence[Site], attr: str) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for s in sites:
        key = getattr(s, attr)
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def md_report(root: Path, sites: Sequence[Site]) -> str:
    lines: List[str] = []
    lines.append("# Stage 3 Direct Command Site Report")
    lines.append("")
    lines.append("Generated by `tools/audit_direct_command_sites.py`.")
    lines.append("")
    lines.append(f"- Source root: `{root.as_posix()}`")
    lines.append(f"- Direct command issue sites: `{len(sites)}`")
    lines.append("")
    lines.append("## Counts by classification")
    lines.append("")
    lines.append("| Classification | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(sites, "classification").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Counts by kind")
    lines.append("")
    lines.append("| Kind | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(sites, "kind").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Sites")
    lines.append("")
    lines.append("| File | Line | Kind | Classification | Source |")
    lines.append("|---|---:|---|---|---|")
    for s in sites:
        src = s.source.replace("|", "\\|")
        lines.append(f"| `{s.path}` | {s.line} | `{s.kind}` | `{s.classification}` | `{src}` |")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("This report intentionally counts likely direct command issue sites, not every `defines.command` reference. It should be used to prioritize Stage 3/4 movement command ownership review. Do not migrate behavior-critical command sites until lifecycle/destruction/state audits are complete enough.")
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Audit direct command issue sites")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--markdown", default=str(MD))
    parser.add_argument("--json", default=str(JSON_OUT))
    parser.add_argument("--context", type=int, default=8)
    args = parser.parse_args(argv)
    root = Path(args.root)
    if not root.exists():
        raise SystemExit(f"missing source root: {root}")
    sites = scan(root, max(0, args.context))
    md = Path(args.markdown)
    js = Path(args.json)
    md.parent.mkdir(parents=True, exist_ok=True)
    js.parent.mkdir(parents=True, exist_ok=True)
    md.write_text(md_report(root, sites), encoding="utf-8")
    js.write_text(json.dumps({
        "source_root": root.as_posix(),
        "total_sites": len(sites),
        "counts_by_classification": counts_by(sites, "classification"),
        "counts_by_kind": counts_by(sites, "kind"),
        "sites": [asdict(s) for s in sites],
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {root}; direct command issue sites={len(sites)}")
    print(f"Wrote {md}")
    print(f"Wrote {js}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
