#!/usr/bin/env python3
from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

ROOT = Path("tech-priests_src")
MD = ROOT / "docs/CODEBASE_AUDIT_STAGE5_MOVEMENT_CONTROLLER_INSTALL_SURFACES.md"
JSON_OUT = ROOT / "docs/CODEBASE_AUDIT_STAGE5_MOVEMENT_CONTROLLER_INSTALL_SURFACES.json"

PATTERNS = (
    "scripts.core.movement_controller",
    "movement_controller",
    "Movement.install",
    ".install()",
    "M.install()",
    "M.patch_globals()",
    "function M.install()",
    "function M.patch_globals()",
    "TECH_PRIESTS_MOVEMENT_CONTROLLER_0418",
    "tech_priests_request_movement_0418 =",
    "tech_priests_request_movement_0418",
    "TECH_PRIESTS_0511_PRE_REQUEST_MOVEMENT_0418",
    "TECH_PRIESTS_0518_PRE_REQUEST_MOVEMENT_0418",
    "tech_priests_route_ground_command_0429 =",
    "tech_priests_stop_movement_0418 =",
)

@dataclass
class Hit:
    path: str
    line: int
    pattern: str
    kind: str
    source: str


def iter_files(root: Path) -> Iterable[Path]:
    for p in root.rglob("*.lua"):
        if ".git" not in p.parts and "__pycache__" not in p.parts:
            yield p


def classify(path: str, source: str, pattern: str) -> str:
    s = source.strip()
    if "require(" in s and "scripts.core.movement_controller" in s:
        return "movement-controller-require"
    if "Movement.install" in s or "movement_controller.install" in s:
        return "movement-controller-install-call-candidate"
    if "function M.install()" in s and path.endswith("movement_controller.lua"):
        return "movement-controller-install-definition"
    if "M.patch_globals()" in s and path.endswith("movement_controller.lua"):
        return "movement-controller-patch-globals-call"
    if "function M.patch_globals()" in s and path.endswith("movement_controller.lua"):
        return "movement-controller-patch-globals-definition"
    if "tech_priests_request_movement_0418 =" in s:
        return "movement-request-global-assignment"
    if "TECH_PRIESTS_0511_PRE_REQUEST_MOVEMENT_0418" in s or "TECH_PRIESTS_0518_PRE_REQUEST_MOVEMENT_0418" in s:
        return "movement-request-wrapper"
    if "tech_priests_request_movement_0418" in s:
        return "movement-request-reference"
    if "tech_priests_route_ground_command_0429 =" in s or "tech_priests_stop_movement_0418 =" in s:
        return "movement-global-assignment"
    if ".install()" in s:
        return "generic-install-call"
    return "reference"


def scan(root: Path) -> List[Hit]:
    hits: List[Hit] = []
    for p in iter_files(root):
        rel = p.relative_to(root).as_posix()
        lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
        for n, line in enumerate(lines, 1):
            for pat in PATTERNS:
                if pat in line:
                    hits.append(Hit(rel, n, pat, classify(rel, line, pat), line.strip()))
    hits.sort(key=lambda h: (h.kind, h.path.lower(), h.line, h.pattern))
    return hits


def counts_by(hits: Sequence[Hit], attr: str) -> Dict[str, int]:
    d: Dict[str, int] = {}
    for h in hits:
        k = str(getattr(h, attr))
        d[k] = d.get(k, 0) + 1
    return dict(sorted(d.items(), key=lambda kv: (-kv[1], kv[0])))


def md(hits: Sequence[Hit]) -> str:
    lines = ["# Stage 5 Movement Controller Install Surface Report", "", "Generated by `tools/audit_movement_controller_install_surfaces.py`.", "", f"- Total hits: `{len(hits)}`", ""]
    for title, attr in (("Counts by kind", "kind"), ("Counts by file", "path"), ("Counts by pattern", "pattern")):
        lines += [f"## {title}", "", "| Value | Count |", "|---|---:|"]
        lines += [f"| `{k}` | {v} |" for k, v in counts_by(hits, attr).items()]
        lines.append("")
    lines += ["## Hits", "", "| Kind | Pattern | File | Line | Source |", "|---|---|---|---:|---|"]
    for h in hits:
        src = h.source.replace("|", "\\|")
        lines.append(f"| `{h.kind}` | `{h.pattern}` | `{h.path}` | {h.line} | `{src}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not ROOT.exists():
        raise SystemExit(f"missing source root: {ROOT}")
    hits = scan(ROOT)
    if not hits:
        raise SystemExit("no movement-controller install surfaces found")
    MD.parent.mkdir(parents=True, exist_ok=True)
    MD.write_text(md(hits), encoding="utf-8")
    JSON_OUT.write_text(json.dumps({
        "total_hits": len(hits),
        "counts_by_kind": counts_by(hits, "kind"),
        "counts_by_file": counts_by(hits, "path"),
        "counts_by_pattern": counts_by(hits, "pattern"),
        "hits": [asdict(h) for h in hits],
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {ROOT}; movement-controller install hits={len(hits)}")
    print(f"Wrote {MD}")
    print(f"Wrote {JSON_OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
