#!/usr/bin/env python3
"""
Audit direct command ownership in Tech Priests source.

This scanner is read-only. It looks for direct movement/combat command surfaces
that can bypass the canonical movement controller or route visible attack command
ownership through older wrappers.

Run from repository root:

    python tools/audit_direct_command_ownership.py

Outputs:

    tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_REPORT.md
    tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_REPORT.json
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence


DEFAULT_ROOT = Path("tech-priests_src")
DEFAULT_MD = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_REPORT.md")
DEFAULT_JSON = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE3_DIRECT_COMMAND_REPORT.json")

PATTERNS = [
    ("set_command", re.compile(r"\bset_command\s*\(")),
    ("commandable_set_command", re.compile(r"\bcommandable\s*\.\s*set_command\s*\(")),
    ("issue_priest_command", re.compile(r"\bissue_priest_command\b")),
    ("defines_command", re.compile(r"\bdefines\s*\.\s*command\b")),
    ("go_to_location", re.compile(r"go_to_location")),
    ("attack_command", re.compile(r"defines\s*\.\s*command\s*\.\s*attack|type\s*=\s*defines\s*\.\s*command\s*\.\s*attack")),
]

CANONICAL_MOVEMENT_PATH = "scripts/core/movement_controller.lua"

@dataclass
class Hit:
    path: str
    line: int
    kind: str
    text: str
    classification: str
    context_before: List[str]
    context_after: List[str]


def iter_lua(root: Path) -> Iterable[Path]:
    for path in root.rglob("*.lua"):
        if ".git" in path.parts or "__pycache__" in path.parts:
            continue
        yield path


def classify(path: str, line: str, blob: str) -> str:
    p = path.replace("\\", "/").lower()
    b = blob.lower()
    if p.endswith(CANONICAL_MOVEMENT_PATH):
        return "canonical-movement-controller"
    if "tech_priests_request_movement_0418" in b and ("elseif" in b or "fallback" in b or "if not" in b):
        return "movement-request-fallback-direct-command"
    if "issue_priest_command" in b and "defines.command.attack" in b:
        return "combat-command-wrapper"
    if "defines.command.attack" in b:
        return "direct-attack-command-review"
    if "go_to_location" in b or "set_command" in b or "commandable.set_command" in b:
        return "direct-movement-command-review"
    return "command-reference-review"


def scan_file(path: Path, root: Path, context: int) -> List[Hit]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    rel = path.relative_to(root).as_posix()
    hits: List[Hit] = []
    for idx, line in enumerate(lines, start=1):
        for kind, pattern in PATTERNS:
            if pattern.search(line):
                before = lines[max(0, idx - 1 - context):idx - 1]
                after = lines[idx:min(len(lines), idx + context)]
                blob = "\n".join(before + [line] + after)
                hits.append(Hit(rel, idx, kind, line.strip(), classify(rel, line, blob), before, after))
    return hits


def scan(root: Path, context: int) -> List[Hit]:
    hits: List[Hit] = []
    for path in iter_lua(root):
        hits.extend(scan_file(path, root, context))
    hits.sort(key=lambda h: (h.path.lower(), h.line, h.kind))
    return hits


def counts_by(hits: Sequence[Hit], attr: str) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for h in hits:
        key = getattr(h, attr)
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def markdown(root: Path, hits: Sequence[Hit]) -> str:
    lines: List[str] = []
    lines.append("# Stage 3 Direct Command Ownership Report")
    lines.append("")
    lines.append("Generated by `tools/audit_direct_command_ownership.py`.")
    lines.append("")
    lines.append(f"- Source root: `{root.as_posix()}`")
    lines.append(f"- Total hits: `{len(hits)}`")
    lines.append("")
    lines.append("## Counts by classification")
    lines.append("")
    lines.append("| Classification | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(hits, "classification").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Counts by kind")
    lines.append("")
    lines.append("| Kind | Count |")
    lines.append("|---|---:|")
    for key, count in counts_by(hits, "kind").items():
        lines.append(f"| `{key}` | {count} |")
    lines.append("")
    lines.append("## Hits")
    lines.append("")
    lines.append("| File | Line | Kind | Classification | Source |")
    lines.append("|---|---:|---|---|---|")
    for h in hits:
        text = h.text.replace("|", "\\|")
        lines.append(f"| `{h.path}` | {h.line} | `{h.kind}` | `{h.classification}` | `{text}` |")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("The canonical owner for ground priest movement commands is expected to be `scripts/core/movement_controller.lua`. Direct movement command hits outside that file should usually be classified as fallbacks or legacy command wrappers before any behavior change is attempted.")
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Audit direct command ownership")
    parser.add_argument("--root", default=str(DEFAULT_ROOT))
    parser.add_argument("--markdown", default=str(DEFAULT_MD))
    parser.add_argument("--json", default=str(DEFAULT_JSON))
    parser.add_argument("--context", type=int, default=6)
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.exists():
        raise SystemExit(f"source root missing: {root}")
    hits = scan(root, max(0, args.context))
    md = Path(args.markdown)
    js = Path(args.json)
    md.parent.mkdir(parents=True, exist_ok=True)
    js.parent.mkdir(parents=True, exist_ok=True)
    md.write_text(markdown(root, hits), encoding="utf-8")
    js.write_text(json.dumps({
        "source_root": root.as_posix(),
        "total_hits": len(hits),
        "counts_by_classification": counts_by(hits, "classification"),
        "counts_by_kind": counts_by(hits, "kind"),
        "hits": [asdict(h) for h in hits],
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {root}; direct-command hits={len(hits)}")
    print(f"Wrote {md}")
    print(f"Wrote {js}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
