#!/usr/bin/env python3
from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

ROOT = Path("tech-priests_src")
MD = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE5_DIRECT_COMMAND_SURFACES.md")
JSON_OUT = Path("tech-priests_src/docs/CODEBASE_AUDIT_STAGE5_DIRECT_COMMAND_SURFACES.json")

PATTERNS = (
    "set_command",
    "commandable.set_command",
    "defines.command.go_to_location",
    "defines.command.attack",
    "defines.command.stop",
    "tech_priests_route_ground_command_0429",
    "tech_priests_request_movement_0418",
    "move_priest_to",
)

@dataclass
class Hit:
    path: str
    line: int
    pattern: str
    kind: str
    source: str


def iter_lua(root: Path) -> Iterable[Path]:
    yield from (p for p in root.rglob("*.lua") if ".git" not in p.parts and "__pycache__" not in p.parts)


def classify(path: str, line: str, pattern: str) -> str:
    if path.endswith("scripts/core/movement_controller.lua"):
        return "canonical-movement-controller"
    if "tech_priests_route_ground_command_0429" in line or "tech_priests_request_movement_0418" in line:
        return "movement-helper-call"
    if "move_priest_to" in line:
        return "legacy-move-helper-call"
    if "set_command" in line or "defines.command" in line:
        return "direct-command-surface"
    return "reference"


def scan(root: Path) -> List[Hit]:
    hits: List[Hit] = []
    for path in iter_lua(root):
        rel = path.relative_to(root).as_posix()
        for i, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            for p in PATTERNS:
                if p in line:
                    hits.append(Hit(rel, i, p, classify(rel, line, p), line.strip()))
    hits.sort(key=lambda h: (h.kind, h.path.lower(), h.line, h.pattern))
    return hits


def counts_by(hits: Sequence[Hit], attr: str) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for h in hits:
        k = str(getattr(h, attr))
        out[k] = out.get(k, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def markdown(hits: Sequence[Hit]) -> str:
    lines = ["# Stage 5 Direct Command Surface Report", "", "Generated by `tools/audit_direct_command_surfaces.py`.", "", f"- Total hits: `{len(hits)}`", ""]
    for title, attr in (("Counts by kind", "kind"), ("Counts by file", "path"), ("Counts by pattern", "pattern")):
        lines += [f"## {title}", "", "| Value | Count |", "|---|---:|"]
        lines += [f"| `{k}` | {v} |" for k, v in counts_by(hits, attr).items()]
        lines.append("")
    lines += ["## Hits", "", "| Kind | Pattern | File | Line | Source |", "|---|---|---|---:|---|"]
    for h in hits:
        src = h.source.replace("|", "\\|")
        lines.append(f"| `{h.kind}` | `{h.pattern}` | `{h.path}` | {h.line} | `{src}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not ROOT.exists():
        raise SystemExit(f"missing source root: {ROOT}")
    hits = scan(ROOT)
    if not hits:
        raise SystemExit("no direct command/movement surfaces found; refusing empty report")
    MD.parent.mkdir(parents=True, exist_ok=True)
    MD.write_text(markdown(hits), encoding="utf-8")
    JSON_OUT.write_text(json.dumps({"total_hits": len(hits), "counts_by_kind": counts_by(hits, "kind"), "counts_by_file": counts_by(hits, "path"), "counts_by_pattern": counts_by(hits, "pattern"), "hits": [asdict(h) for h in hits]}, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {ROOT}; direct command surface hits={len(hits)}")
    print(f"Wrote {MD}")
    print(f"Wrote {JSON_OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
