#!/usr/bin/env python3
from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

ROOT = Path("tech-priests_src")
MD = ROOT / "docs/CODEBASE_AUDIT_STAGE5_MOVEMENT_COMPLETION_CONSUMERS.md"
JSON_OUT = ROOT / "docs/CODEBASE_AUDIT_STAGE5_MOVEMENT_COMPLETION_CONSUMERS.json"

REQUEST_PATTERNS = (
    "tech_priests_request_movement_0418",
    "tech_priests_route_ground_command_0429",
    "move_priest_to",
    "request_move(",
    "set_move(",
    "return_to_station(",
    "M.request(",
)

STATUS_PATTERNS = (
    "tech_priests_movement_status_0418",
    "request_status(",
    "movement_controller_status_0418",
    "movement_request_0418",
    "movement_controller_state_0418",
    "movement_controller_clamp_0418",
    "expires_tick",
    "last_command_tick",
    "last_distance_sq",
)

PROXIMITY_PATTERNS = (
    "dist_sq(",
    "distance_sq",
    "pickup_radius_sq",
    "machine_reach_sq",
    "storage_reach_sq",
    "repair_reach_sq",
    "rite_reach_sq",
    "build_reach_sq",
    "radius",
)

PHASE_PATTERNS = (
    "moving-to-",
    "move-to-",
    "walk-to-",
    "returning-to-",
    "travelling-to-",
    "waiting-",
    "loitering",
    "arrived",
    "complete",
    "movement-request-failed",
)

@dataclass
class Hit:
    path: str
    line: int
    kind: str
    pattern: str
    source: str


def iter_lua(root: Path) -> Iterable[Path]:
    for p in root.rglob("*.lua"):
        if ".git" not in p.parts and "__pycache__" not in p.parts:
            yield p


def scan() -> List[Hit]:
    hits: List[Hit] = []
    pattern_groups = [
        ("movement-request", REQUEST_PATTERNS),
        ("movement-status-or-state", STATUS_PATTERNS),
        ("proximity-or-radius-check", PROXIMITY_PATTERNS),
        ("movement-phase-string", PHASE_PATTERNS),
    ]
    for path in iter_lua(ROOT):
        rel = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        for n, line in enumerate(text.splitlines(), 1):
            s = line.strip()
            for kind, pats in pattern_groups:
                for pat in pats:
                    if pat in line:
                        hits.append(Hit(rel, n, kind, pat, s))
    hits.sort(key=lambda h: (h.path.lower(), h.line, h.kind, h.pattern))
    return hits


def counts_by(hits: Sequence[Hit], attr: str) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for h in hits:
        k = str(getattr(h, attr))
        out[k] = out.get(k, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def file_summary(hits: Sequence[Hit]) -> List[Dict[str, object]]:
    by_file: Dict[str, Dict[str, int]] = {}
    for h in hits:
        d = by_file.setdefault(h.path, {})
        d[h.kind] = d.get(h.kind, 0) + 1
    rows: List[Dict[str, object]] = []
    for path, counts in by_file.items():
        request = counts.get("movement-request", 0)
        status = counts.get("movement-status-or-state", 0)
        proximity = counts.get("proximity-or-radius-check", 0)
        phase = counts.get("movement-phase-string", 0)
        risk = "low"
        if request and phase and not status:
            risk = "high-no-status"
        elif request and phase and status:
            risk = "review-status-use"
        elif request and not status:
            risk = "medium-request-only"
        elif phase and not status:
            risk = "medium-phase-only"
        rows.append({
            "path": path,
            "risk_hint": risk,
            "movement_request": request,
            "movement_status_or_state": status,
            "proximity_or_radius_check": proximity,
            "movement_phase_string": phase,
            "total": request + status + proximity + phase,
        })
    rows.sort(key=lambda r: (str(r["risk_hint"]) != "high-no-status", -int(r["total"]), str(r["path"])))
    return rows


def md(hits: Sequence[Hit]) -> str:
    rows = file_summary(hits)
    lines = [
        "# Stage 5 Movement Completion Consumer Report",
        "",
        "Generated by `tools/audit_movement_completion_consumers.py`.",
        "",
        "This report inventories modules that request movement, report movement phases, poll proximity, or read movement status/state.",
        "It does not prove correctness by itself. It identifies files that need manual review for movement completion/failure consumption.",
        "",
        f"- Total hits: `{len(hits)}`",
        f"- Files with hits: `{len(rows)}`",
        "",
        "## Counts by kind",
        "",
        "| Kind | Count |",
        "|---|---:|",
    ]
    for k, v in counts_by(hits, "kind").items():
        lines.append(f"| `{k}` | {v} |")
    lines += ["", "## File summary", "", "| Risk hint | File | Request | Status/state | Proximity | Phase strings | Total |", "|---|---|---:|---:|---:|---:|---:|"]
    for r in rows:
        lines.append(f"| `{r['risk_hint']}` | `{r['path']}` | {r['movement_request']} | {r['movement_status_or_state']} | {r['proximity_or_radius_check']} | {r['movement_phase_string']} | {r['total']} |")
    lines += ["", "## Hits", "", "| File | Line | Kind | Pattern | Source |", "|---|---:|---|---|---|"]
    for h in hits:
        src = h.source.replace("|", "\\|")
        lines.append(f"| `{h.path}` | {h.line} | `{h.kind}` | `{h.pattern}` | `{src}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not ROOT.exists():
        raise SystemExit(f"missing source root: {ROOT}")
    hits = scan()
    if not hits:
        raise SystemExit("no movement completion consumer hits found")
    MD.parent.mkdir(parents=True, exist_ok=True)
    MD.write_text(md(hits), encoding="utf-8")
    JSON_OUT.write_text(json.dumps({
        "total_hits": len(hits),
        "counts_by_kind": counts_by(hits, "kind"),
        "counts_by_file": counts_by(hits, "path"),
        "file_summary": file_summary(hits),
        "hits": [asdict(h) for h in hits],
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Scanned {ROOT}; movement completion consumer hits={len(hits)}")
    print(f"Wrote {MD}")
    print(f"Wrote {JSON_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
