-- Tech Priests 0.1.227
-- Planetary Magos reserved-name registry.
--
-- Purpose:
--   These names are reserved for living players / special recognition targets.
--   If a player joins with an exact or partial match, the name is removed from
--   the Planetary Magos name pool and any existing Magos using that cell name is
--   renamed away from it.  This avoids the uncanny situation where the player
--   meets a command-rank priest wearing their own name.
--
-- Notes:
--   Lines are intentionally brief, celebratory, and safe.  They are written as
--   in-universe acknowledgements inspired by public creator/developer/community
--   reputations where broadly known, and by the literal handle otherwise.

return {
  names = {
    { key = "nilaus", display = "Nilaus", line = "High Fabricator Nilaus detected. Main-bus discipline and city-block liturgy are entered into the command archive." },
    { key = "trupen", display = "Trupen", line = "High Fabricator Trupen detected. Chaotic instructional doctrine has entered the shrine and all safety signage is now advisory." },
    { key = "doshdoshington", display = "DoshDoshington", aliases = { "dosh" }, line = "High Fabricator DoshDoshington detected. Challenge-run heresy has been reclassified as peer-reviewed engineering." },
    { key = "katherineofsky", display = "KatherineOfSky", aliases = { "katherine of sky", "kos" }, line = "High Fabricator KatherineOfSky detected. The skyward factory paths are acknowledged with reverence." },
    { key = "xterminator", display = "Xterminator", line = "High Fabricator Xterminator detected. Megabase commentary protocols and extermination-grade throughput analysis are authorized." },
    { key = "michaelhendriks", display = "Michael Hendriks", aliases = { "michael hendriks" }, line = "High Fabricator Michael Hendriks detected. Deathworld endurance doctrine is granted a respectful perimeter." },
    { key = "jdplays", display = "JD-Plays", aliases = { "jd plays", "jd-plays" }, line = "High Fabricator JD-Plays detected. Factory observation rites are online and the bus is under review." },
    { key = "tuplex", display = "Tuplex", line = "High Fabricator Tuplex detected. Tutorial-grade logistics are promoted to Magos consideration." },
    { key = "yamakara", display = "Yama Kara", aliases = { "yama kara" }, line = "High Fabricator Yama Kara detected. Long-form factory doctrine enters the command record." },
    { key = "antielitz", display = "AntiElitz", line = "High Fabricator AntiElitz detected. Speed and execution doctrine have arrived ahead of schedule." },
    { key = "nefrums", display = "Nefrums", line = "High Fabricator Nefrums detected. Speedrun precision rites are now operating faster than the junior priesthood can annotate." },
    { key = "martincitopants", display = "martincitopants", line = "High Fabricator martincitopants detected. The archive notes severe comedic instability and approves it anyway." },
    { key = "thespiffingbrit", display = "The Spiffing Brit", aliases = { "spiffing brit", "the spiffing brit" }, line = "High Fabricator The Spiffing Brit detected. Perfectly balanced doctrine is expected and absolutely not exploited." },
    { key = "krydax", display = "Krydax", line = "High Fabricator Krydax detected. Modded factory doctrine is opened for responsible overcomplication." },
    { key = "docjade", display = "DocJade", line = "High Fabricator DocJade detected. Diagnostic jade protocols are ready for consultation." },
    { key = "autocraft", display = "Autocraft", line = "High Fabricator Autocraft detected. Automated construction liturgies recognize a familiar signature." },
    { key = "minibetrayal", display = "MiniBetrayal", line = "High Fabricator MiniBetrayal detected. Small-scale treachery is filed under acceptable emergent behavior." },
    { key = "boldviking", display = "Bold Viking", aliases = { "bold viking" }, line = "High Fabricator Bold Viking detected. Northern boldness is accepted into the forge ledger." },
    { key = "arumba", display = "Arumba", line = "High Fabricator Arumba detected. Spreadsheet-adjacent optimization spirits have become attentive." },
    { key = "mangledporkgaming", display = "MangledPork Gaming", aliases = { "mangledpork", "mangled pork gaming" }, line = "High Fabricator MangledPork Gaming detected. The pork is mangled; the factory remains negotiable." },
    { key = "colonelwill", display = "ColonelWill", line = "High Fabricator ColonelWill detected. Command voice recognized; local cohorts are standing less incorrectly." },
    { key = "negativeroot", display = "Negative Root", aliases = { "negative root" }, line = "High Fabricator Negative Root detected. Root-cause analysis has entered negative space and returned with throughput." },
    { key = "zisteau", display = "Zisteau", line = "High Fabricator Zisteau detected. The old archives stir with appropriately engineered mischief." },
    { key = "aavak", display = "Aavak", line = "High Fabricator Aavak detected. Calm narration protocols are welcome within the shrine." },
    { key = "quill18", display = "Quill18", line = "High Fabricator Quill18 detected. Strategic annotation and colony-grade reasoning are accepted." },
    { key = "manyatruenerd", display = "Many A True Nerd", aliases = { "many a true nerd", "matn" }, line = "High Fabricator Many A True Nerd detected. The doctrine appreciates both survival math and glorious bad ideas." },
    { key = "skyestorme", display = "Skye Storme", aliases = { "skye storme" }, line = "High Fabricator Skye Storme detected. Atmospheric turbulence has been reclassified as presentation flair." },
    { key = "sips", display = "Sips", line = "High Fabricator Sips detected. The factory braces for relaxed competence and improbable disaster." },
    { key = "direwolf20", display = "Direwolf20", line = "High Fabricator Direwolf20 detected. Modded automation instincts are granted honorary cogitation clearance." },
    { key = "zyllius", display = "Zyllius", line = "High Fabricator Zyllius detected. The name is entered into the Magos registry with careful binning." },
    { key = "qon", display = "Qon", line = "High Fabricator Qon detected. Minimal glyph, maximal administrative consequence." },
    { key = "tobiasspringer", display = "Tobias Springer", aliases = { "tobias springer" }, line = "High Fabricator Tobias Springer detected. Springer protocols are accepted by the planetary lexicon." },
    { key = "warger", display = "Warger", line = "High Fabricator Warger detected. The registry growls approvingly." },
    { key = "thue", display = "Thue", line = "High Fabricator Thue detected. Compact nomenclature receives full command honors." },
    { key = "teamsteelaxe", display = "Team Steelaxe", aliases = { "team steelaxe" }, line = "High Fabricator Team Steelaxe detected. Steel and axe doctrine are both considered industrially legible." },
    { key = "rain9441", display = "Rain9441", line = "High Fabricator Rain9441 detected. Atmospheric water rites have become suspiciously attentive." },
    { key = "typicalguy", display = "typical_guy", aliases = { "typical guy", "typical_guy" }, line = "High Fabricator typical_guy detected. Typicality has been escalated to exceptional clearance." },
    { key = "flaggi793", display = "Flaggi793", line = "High Fabricator Flaggi793 detected. The banner is raised; the digits are sanctified." },
    { key = "seky16", display = "seky16", line = "High Fabricator seky16 detected. Sixteenfold notation acknowledged." },
    { key = "cobai", display = "Cobai", line = "High Fabricator Cobai detected. The cogitators accept the designation without complaint." },
    { key = "krul87", display = "Krul87", line = "High Fabricator Krul87 detected. Eighty-seven minor litanies are implied and one major one is pending." },
    { key = "guuna", display = "Guuna", line = "High Fabricator Guuna detected. The lexigraphic registry hums in assent." },
    { key = "aclegend", display = "ACLegend", line = "High Fabricator ACLegend detected. Legendary conditioning is not yet proven, but strongly suspected." },
    { key = "wollywog", display = "Wollywog", line = "High Fabricator Wollywog detected. Amphibious nomenclature has been given dry-floor privileges." },
    { key = "bilka", display = "Bilka", line = "High Fabricator Bilka detected. Wiki-admin and Wube-adjacent rites are treated with unusual respect." },
    { key = "jansharp", display = "JanSharp", line = "High Fabricator JanSharp detected. Sharpness of implementation is assumed until disproven by stack trace." },
    { key = "markiplier", display = "Markiplier", line = "High Fabricator Markiplier detected. The shrine has increased volume and emotional range accordingly." },
    { key = "sovietwomble", display = "SovietWomble", line = "High Fabricator SovietWomble detected. Bullshittery has been filed under advanced social automation." },
    { key = "giantwaffle", display = "Giantwaffle", line = "High Fabricator Giantwaffle detected. Breakfast-scale throughput exceeds local belt capacity." },
    { key = "pointcrow", display = "PointCrow", line = "High Fabricator PointCrow detected. The avian pointer has entered the machine registry." },

    { key = "w4stedspace", display = "w4stedspace", line = "High Fabricator w4stedspace detected. The void was already wasted; now it is organized." },
    { key = "moos3h", display = "moos3h", line = "High Fabricator moos3h detected. Numeral-inflected designation accepted." },
    { key = "orbitalstorms", display = "OrbitalStorms", line = "High Fabricator OrbitalStorms detected. Orbital weather doctrine is now everyone else's problem." },
    { key = "sable", display = "Sable", line = "High Fabricator Sable detected. Dark-fiber naming accepted into the command weave." },
    { key = "sharkeymyrl", display = "SharkeyMyrl", line = "High Fabricator SharkeyMyrl detected. Aquatic threat profile upgraded to advisory." },
    { key = "susurrus", display = "Susurrus", line = "High Fabricator Susurrus detected. The whispering machine spirits have become organized." },
    { key = "affrighting", display = "Affrighting", line = "High Fabricator Affrighting detected. Fear response logged; productivity unaffected." },
    { key = "arthour05", display = "arthour05", line = "High Fabricator arthour05 detected. Hour five is reserved for ritual maintenance." },
    { key = "axuryi", display = "Axuryi", line = "High Fabricator Axuryi detected. Exotic glyph chain accepted." },
    { key = "bigd9991", display = "BigD9991", line = "High Fabricator BigD9991 detected. Large designation; larger administrative suffix." },
    { key = "bonnieb", display = "BonnieB", line = "High Fabricator BonnieB detected. Double-B registry lock engaged." },
    { key = "cajunseph", display = "cajun_seph", aliases = { "cajun seph", "cajun_seph" }, line = "High Fabricator cajun_seph detected. Spiced logistics are entered into the shrine ledger." },
    { key = "chride", display = "Chride", line = "High Fabricator Chride detected. The registry accepts the ride and asks no further questions." },
    { key = "creepymonkey", display = "CreepyMonkey", line = "High Fabricator CreepyMonkey detected. Arboreal unease is tolerated near the machine altar." },
    { key = "dariorthan", display = "Dariorthan", line = "High Fabricator Dariorthan detected. The name requires a wider plaque and has been granted one." },
    { key = "faith", display = "Faith", line = "High Fabricator Faith detected. Belief has entered a machine-readable format." },
    { key = "frosty", display = "Frosty", line = "High Fabricator Frosty detected. Cryogenic respect protocols are now active." },
    { key = "gromnir86", display = "gromnir86", line = "High Fabricator gromnir86 detected. The eighty-sixth grumble has been blessed." },
    { key = "iodine", display = "Iodine", line = "High Fabricator Iodine detected. Chemical notation accepted; stains expected." },
    { key = "jeepguy85", display = "JeepGuy85", line = "High Fabricator JeepGuy85 detected. Wheeled doctrine is considered plausible." },
    { key = "khaalbergstrom", display = "Khaal Bergstrom", aliases = { "khaal bergstrom" }, line = "High Fabricator Khaal Bergstrom detected. The registry salutes with excessive consonants." },
    { key = "kolorowywyzel", display = "KolorowyWyzel", line = "High Fabricator KolorowyWyzel detected. Chromatic designation approved." },
    { key = "laughedlizard", display = "LaughedLizard", line = "High Fabricator LaughedLizard detected. Reptilian amusement has been localized." },
    { key = "lokiulrich", display = "LokiUlrich", line = "High Fabricator LokiUlrich detected. Trickster variance accepted under supervision." },
    { key = "matitaus", display = "Matitaus", line = "High Fabricator Matitaus detected. The name is etched in black cogitator wax." },
    { key = "oreoleo", display = "oreoleo", line = "High Fabricator oreoleo detected. Ore repetition doctrine finds this pleasing." },
    { key = "pandamarsh", display = "pandamarsh", line = "High Fabricator pandamarsh detected. Marshland panda logistics are approved for dry storage." },
    { key = "pepper", display = "Pepper", line = "High Fabricator Pepper detected. Seasoning has been added to the production queue." },
    { key = "ptolus", display = "Ptolus", line = "High Fabricator Ptolus detected. Silent letters have been granted clearance." },
    { key = "raigy", display = "Raigy", line = "High Fabricator Raigy detected. The designation crackles at acceptable voltage." },
    { key = "redstoner", display = "RedStoner", line = "High Fabricator RedStoner detected. Redstone habits will be tolerated near circuits but watched carefully." },
    { key = "relo", display = "Relo", line = "High Fabricator Relo detected. Relocation doctrine begins immediately." },
    { key = "retovath", display = "Retovath", line = "High Fabricator Retovath detected. The registry pronounces it confidently and refuses correction." },
    { key = "synaxis", display = "Synaxis", line = "High Fabricator Synaxis detected. Assembly of names and machines is underway." },
    { key = "t0rchfire", display = "T0RCHFIRE", aliases = { "torchfire", "t0rchfire" }, line = "High Fabricator T0RCHFIRE detected. Ignition doctrine is authorized but supervised." },
    { key = "ursusrobusta", display = "UrsusRobusta", line = "High Fabricator UrsusRobusta detected. Bear-grade robustness accepted." },
    { key = "validustv", display = "Validus TV", aliases = { "validus tv" }, line = "High Fabricator Validus TV detected. Broadcast validity has been sanctified." },
    { key = "xpmexe", display = "XPM.exe", aliases = { "xpm.exe", "xpm exe" }, line = "High Fabricator XPM.exe detected. Executable designation has requested admin privileges and been denied politely." },
    { key = "xyph3r", display = "Xyph3r", line = "High Fabricator Xyph3r detected. Ciphered glyphs are now under Magos protection." },
  }
}
